-- AlterEnum
ALTER TYPE "VerificationType" ADD VALUE 'PASSWORD_RESET';

-- AlterEnum
ALTER TYPE "AuditEvent" ADD VALUE 'PASSWORD_RESET_REQUESTED';
ALTER TYPE "AuditEvent" ADD VALUE 'PASSWORD_RESET_COMPLETED';
ALTER TYPE "AuditEvent" ADD VALUE 'PASSWORD_RESET_FAILED';
